### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by kimrutherford** [pombase/allele_qc#16]
Hi Manu.

I've been going through the README.  I have an error at the `bash get_data.sh` step:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1575k  100 1575k    0     0   500k      0  0:00:03  0:00:03 --:--:--  500k
Loading the genome
Traceback (most recent call last):
  File "/u/allele_qc/load_sequences.py", line 41, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'
Traceback (most recent call last):
  File "/u/allele_qc/load_genome.py", line 18, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'
Getting coordinate changes
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  394k  100  394k    0     0   549k      0 --:--:-- --:--:-- --:--:--  549k
```

**Comment by kimrutherford** [comment]
Fixed with:

```sh
apt install gcc python3.10-dev
```

before running `poetry install`
