### ISSUE TITLE
Add format parameter to /genome_region

### ISSUE THREAD

**Issue by kimrutherford** [pombase/allele_qc#44]
Hi @manulera 

Sorry, I planned to make this a pull request, but I accidentally push it to master instead:
https://github.com/pombase/allele_qc/commit/ef5789a9dff0e01198c73b844798cf0cd659ca36

This change is so we can download as EMBL format.  What do you think?

Maybe the format should be "genbank" by default?

**Comment by kimrutherford** [comment]
> This change is so we can download as EMBL format. 

Unfortunately I get "Internal Server Error" if the format is "embl".  It works fine with "genbank" and "fasta".

```
INFO:     10.255.0.2:41140 - "GET /genome_region?systematic_id=SPCC18B5.11c&format=embl&upstream=0&downstream=0 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/api/./api.py", line 401, in get_genome_region
    SeqIO.write(rv, fp, format)
  File "/usr/local/lib/python3.10/site-packages/Bio/SeqIO/__init__.py", line 524, in write
    count = writer_class(handle).write_file(sequences)
  File "/usr/local/lib/python3.10/site-packages/Bio/SeqIO/Interfaces.py", line 234, in write_file
    count = self.write_records(records, maxcount)
  File "/usr/local/lib/python3.10/site-packages/Bio/SeqIO/Interfaces.py", line 208, in write_records
    self.write_record(record)
  File "/usr/local/lib/python3.10/site-packages/Bio/SeqIO/InsdcIO.py", line 1415, in write_record
    self._write_the_first_lines(record)
  File "/usr/local/lib/python3.10/site-packages/Bio/SeqIO/InsdcIO.py", line 1245, in _write_the_first_lines
    raise ValueError("Cannot have spaces in EMBL accession, '%s'" % accession)
ValueError: Cannot have spaces in EMBL accession, '<unknown id>'
```

**Comment by kimrutherford** [comment]
I don't know if this is the correct fix, but it seems to work: 09efb37ba875b909e6c7b480e17a92255f68975f

**Comment by manulera** [comment]
Looks sensible, BioPython is extremely pedantic so anything that circumvents those kind of restrictions makes me happy (it won't even tolerate sequence ids that are too long...)

**Comment by kimrutherford** [comment]
> BioPython is extremely pedantic so anything that circumvents those kind of restrictions makes me happy

:-)

On the plus side the GenBank and EMBL output BioPython produces seem to be correct.  Or at least they are correct enough to be read by Artemis.

**Comment by manulera** [comment]
We could make this accept a set of pre-defined options (`embl`, `fasta`, `genbank`). I can do it easily. Alternatively we can leave it as is and close. Let me know.

**Comment by kimrutherford** [comment]
> We could make this accept a set of pre-defined options (embl, fasta, genbank).

I think that's a good idea.  Thanks.

**Comment by manulera** [comment]
Done, I will close with this then
